### ISSUE TITLE
Ensure in the circuit we consistently use `N - x`, not `x - N` (when they are equivalent)

### ISSUE THREAD

**Issue by str4d** [zcash/orchard#143]
We use a mix of these in various equivalent places throughout the circuit, and we also don't always match what is specified in the Orchard book.

**Comment by daira** [comment]
We changed our mind, partly because there's a `Polynomial::one_minus` function and we'd have to change uses of that. Also 1 - x seems to be more common for booleans (possibly because of legacy habits from libsnark).

**Comment by str4d** [comment]
This does make the range-constraint case `x(1 - x)(2 - x)...` a bit weird though, since it's semantically `(0 - x)(1 - x)(2 - x)...` (we'd need to make sure the `0` case is handled specially).

**Comment by str4d** [comment]
We should go through the circuit and make a list of all the places we use this syntax, so we can decide which way to go (@ebfull has opinions I'm hoping he will share here).

**Comment by therealyingtong** [comment]
- `circuit::gadget::utilities`
    - `bool_check()` uses `1 - x`. (Note: `bool_check()` should be re-written as a special case of `range_check()`.)
    - `range_check()` uses `x - N`
    - `utilities::cond_swap`: `configure()`'s `bool_check` should be replaced with `utilities::bool_check()`.
- `ecc::chip`
    - `add.rs`: `create_gate()`'s `poly2, poly{7..=12}` expressions use `(1 - x)`.
    - `mul_fixed.rs`:
        - `coords_check()` `on_curve` check uses `y^2 - x^3 - b`.
        - `mul_fixed::short`: `create_gate()`'s `sign_check` uses `x^2 - 1`; its `last_window_check` should be replaced with `utilities::bool_check()`.
    - `mul.rs`:
        - `create_gate()`'s `bool_check`  should be replaced with `utilities::bool_check()`.
        - `mul::complete`: `create_gate()'s` `bool_check`  should be replaced with `utilities::bool_check()`.
        - `mul::incomplete`: `create_gate()'s` `bool_check`  should be replaced with `utilities::bool_check()`.
        - `mul::overflow`: `create_gate()` uses `x - N` for its `recovery` and `lo_zero` checks; and `1 - x` for its `canonicity` check.
    - `witness_point.rs`: `create_gate()`'s `curve_eqn` closure uses `y^2 - x^3 - b`.

**Comment by therealyingtong** [comment]
I prefer `N - x` because it doesn't result in a negative value when `x < N`.

**Comment by str4d** [comment]
Closed by #235, merged into #237.
