### ISSUE TITLE
Extract gadgets into their own crates

### ISSUE THREAD

**Issue by therealyingtong** [zcash/orchard#183]
This will allow us to add a `poseidon` dependency in `halo2`, without introducing a circular dependency on the `orchard` crate.

Similarly, we can consider extracting `primitives::sinsemilla` into a crate.

Edit:

Let's extract all gadgets/chips/primitives into their own crates. These crates can live in a workspace repo (like `zcash/halo2-gadgets`).

**Comment by str4d** [comment]
I'm +1 on this. I had already secured the `sinsemilla` crate name for this purpose.

I'm inclined to make a single repo for `halo2` gadgets / chips / primitives, which is a workspace of crates like `poseidon` and `sinsemilla`. This can be extracted pretty easily from the current repo with `git filter-branch` (`git subtree` is unnecessary as we wouldn't be keeping them in `orchard`, and it also can't extract multiple directories at once).

**Comment by str4d** [comment]
A single workspace, like we have at `zcash/librustzcash`, is preferable here I think because these crates would have a strong dependency on `halo2`, so we'd want to perform updates to them synchronously. We could also move the SHA-256 example gadget from `halo2` into this workspace.

**Comment by parazyd** [comment]
> I'm +1 on this. I had already secured the `sinsemilla` crate name for this purpose.
> 
> I'm inclined to make a single repo for `halo2` gadgets / chips / primitives, which is a workspace of crates like `poseidon` and `sinsemilla`. This can be extracted pretty easily from the current repo with `git filter-branch` (`git subtree` is unnecessary as we wouldn't be keeping them in `orchard`, and it also can't extract multiple directories at once).

I think this would be very useful, as it empowers external devs and can unify contributions.

**Comment by str4d** [comment]
Should the book pages about these gadgets be moved as well? I think yes, and then in the Orchard book we would reference the new repo's book for the specific instantiation / circuit constraints we are using.

**Comment by str4d** [comment]
Closed by #217.
