### ISSUE TITLE
`circuit.rs`: Remove superfluous Poseidon assignment

### ISSUE THREAD

**Issue by therealyingtong** [zcash/orchard#214]
We are currently assigning `nk`, `rho_old` manually just to cast them from `CellValue` into `StateWord`. There is no need to do this, since `StateWord`s are copied into the Poseidon gadget anyway.

https://github.com/zcash/orchard/blob/4f9c0be42eabcf3cb79916b1a4af61844c3a3d8b/src/circuit.rs#L488-L510

**Comment by str4d** [comment]
Closed by #224, merged into #237.
