### ISSUE TITLE
Fix incorrect namespace in circuit debug code

### ISSUE THREAD

**Issue by str4d** [zcash/orchard#329]
```rust
layouter.namespace(|| "rivk"),
```

_Originally posted by @daira in https://github.com/zcash/orchard/pull/327#discussion_r869812422_

This doesn't technically matter for `orchard 0.1.0` because the layouter is never invoked in `ScalarFixed::new` when using `EccChip`. But we should fix this anyway in case we change this in a future circuit version.

**Comment by daira** [comment]
Also https://github.com/zcash/orchard/pull/327#discussion_r869818494
