### ISSUE TITLE
Implement note commitment tree logic for Orchard

### ISSUE THREAD

**Issue by str4d** [zcash/orchard#33]
Ideally this logic will be shared with Sapling.

- https://zips.z.cash/protocol/nu5.pdf#merkletree
- https://zips.z.cash/protocol/nu5.pdf#commitmentsandnullifiers

**Comment by nuttycom** [comment]
Incremental Merkle tree is ready for review here: https://github.com/ebfull/incrementalmerkletree/pull/1

**Comment by str4d** [comment]
Closed by https://github.com/zcash/orchard/pull/122.
