### ISSUE TITLE
book: Add rationale for excluding ivk = 0, KA^Orchard being zero

### ISSUE THREAD

**Issue by str4d** [zcash/orchard#62]
Summary of pairing w/ @daira: In the action circuit, we have some points (ak^P, cm^old, and pk_d^old) are represented as affine coordinates in the input to the circuit. If they could be zero, we'd need to special-case these points (since the identity can't be represented on the curve). Also makes security analysis easier: if either secret is zero then the shared secret is zero, which removes contributory behaviour (if at least one user contributes randomness then the shared secret is random).

**Comment by daira** [comment]
Subtle point: ivk can't be zero because Commit<sup>ivk</sup> never returns zero. It returns ⊥ instead, because the outer addition that adds blinding in SinsemillaShortCommit is an incomplete addition.
