### ISSUE TITLE
Rename Bundle::{try_}authorize to Bundle::{try_}map_authorization

### ISSUE THREAD

**Issue by str4d** [zcash/orchard#71]
> I'm applying this change so that I can base additional work on it; if there's disagreement we can revisit later.

_Originally posted by @nuttycom in https://github.com/zcash/orchard/pull/70#discussion_r618403592_

**Comment by str4d** [comment]
I disagree because this method does not fully authorize the bundle except in one specific case (where `U` is `Authorized`).

**Comment by nuttycom** [comment]
It doesn't fit the correct signature for `map` - but any other name would be fine.
